# This file contains values from Cookiecutter

default_context:
  project_name: "vinstaller"
  project_description: "A vLifeLong Project created by Martokk."
  organization: "v3services"
  license: "MIT"
  minimal_python_version: "3.10"
  github_name: "martokk"
  email: "25113632+martokk@users.noreply.github.com"
  version: "0.1.0"
  line_length: "79"
  create_example_template: "cli"
